name: Release (Tag)
on:
  push:
    tags: ['v*.*.*']
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          always-auth: true
          scope: '@identityofsine'
          cache: npm
      - run: npm ci
      - run: npm run test
      - name: Skip if version already exists on npm
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "Tag version: $VERSION"
          if npm view @identityofsine/radioactive-forms@"$VERSION" version >/dev/null 2>&1; then
            echo "Version $VERSION already exists on npm. Skipping publish.";
            echo "skip_publish=true" >> $GITHUB_OUTPUT;
          else
            echo "skip_publish=false" >> $GITHUB_OUTPUT;
          fi
        id: check
      - run: npm publish --provenance --access public
        if: steps.check.outputs.skip_publish == 'false'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


